"""Shared domain contracts and deterministic gate helpers."""

from galatiq_invoices.domain.gates import (
    approval_gate,
    evaluate_approval_gate,
    evaluate_ingestion_gate,
    evaluate_payment_gate,
    evaluate_validation_gate,
    ingestion_gate,
    payment_gate,
    validation_gate,
)
from galatiq_invoices.domain.models import (
    AgentResult,
    ApprovalDecision,
    ApprovalStatus,
    DecisionStatus,
    GateDecision,
    GateStatus,
    Invoice,
    IssueCategory,
    IssueSeverity,
    LineItem,
    PaymentResult,
    PaymentStatus,
    Severity,
    ValidationIssue,
    WorkflowResult,
    WorkflowStatus,
)

__all__ = [
    "AgentResult",
    "ApprovalDecision",
    "ApprovalStatus",
    "DecisionStatus",
    "GateDecision",
    "GateStatus",
    "Invoice",
    "IssueCategory",
    "IssueSeverity",
    "LineItem",
    "PaymentResult",
    "PaymentStatus",
    "Severity",
    "ValidationIssue",
    "WorkflowResult",
    "WorkflowStatus",
    "approval_gate",
    "evaluate_approval_gate",
    "evaluate_ingestion_gate",
    "evaluate_payment_gate",
    "evaluate_validation_gate",
    "ingestion_gate",
    "payment_gate",
    "validation_gate",
]

